### PR TITLE
push to your branch

### PR DESCRIPTION
**Pull request by xuanzhao**
add a play model and ignore

### CODE REVIEW

**Comment by xuanzhao** [comment]
try talk each other

**Comment by BrambleXu** [comment]
Hi, it seems there is a conflict in the result.csv file.

**Comment by xuanzhao** [comment]
how to handle that?

**Comment by BrambleXu** [comment]
We have to solve this problem locally.
I hope we could use your file to replace the original file

**Comment by xuanzhao** [comment]
ok, resolve that conflict by yourself, then I could see the result.

**Comment by BrambleXu** [comment]
Hi, I delete the result file in the dev branch. 
It seems we can merge this request :)

**Comment by xuanzhao** [comment]
the best way does not delete the file, try to fix the conflict, then merge them.

**Comment by BrambleXu** [comment]
Ok, we can talk this detailly in private

**Comment by BrambleXu** [comment]
Hi, ken. I found a very useful notebook about our project. Here is link:
https://www.kaggle.com/hhllcks/ghouls-goblins-and-ghosts-boo/comparison-between-classifiers/comments

**Pull request merged**
